/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Budgetrange =
	| "RANGE_10K_25K"
	| "RANGE_25K_50K"
	| "RANGE_50K_PLUS"
	| "RANGE_5K_10K";

export type Contractstatus = "DRAFT" | "EXPIRED" | "SENT" | "SIGNED" | "VIEWED";

export type Emailstatus = "BOUNCED" | "FAILED" | "SENT";

export type Filetype =
	| "CSS"
	| "JSON"
	| "MARKDOWN"
	| "OTHER"
	| "SCSS"
	| "TYPESCRIPT"
	| "TYPESCRIPT_RX";

export type Generated<T> =
	T extends ColumnType<infer S, infer I, infer U>
		? ColumnType<S, I | undefined, U>
		: ColumnType<T, T | undefined, T>;

export type Invoicestatus = "OVERDUE" | "PAID" | "PENDING" | "UNPAID";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export interface JsonObject {
	[x: string]: JsonValue | undefined;
}

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Leadstatus =
	| "CLOSED"
	| "CONTACTED"
	| "CONVERTED"
	| "MEETING_COMPLETED"
	| "MEETING_SCHEDULED"
	| "NEW";

export type Meetingstatus = "CANCELLED" | "COMPLETED" | "NO_SHOW" | "SCHEDULED";

export type Numeric = ColumnType<string, number | string, number | string>;

export type Projectstatus =
	| "CANCELLED"
	| "COMPLETED"
	| "IN_PROGRESS"
	| "ON_HOLD"
	| "PENDING";

export type Projecttype =
	| "AI_AUTOMATION"
	| "BRAND_IDENTITY"
	| "FULL_PRODUCT"
	| "WEB_MOBILE";

export type Role = "ADMIN" | "CUSTOMER";

export type Surveyinputtype = "MULTIPLE_CHOICE" | "SINGLE_CHOICE";

export type Surveyquestiontype = "BUDGET" | "PROJECT_TYPE";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface _AutomationToTag {
	A: string;
	B: string;
}

export interface _BlogPostToTag {
	A: string;
	B: string;
}

export interface Account {
	accessToken: string | null;
	accessTokenExpiresAt: Timestamp | null;
	accountId: string;
	createdAt: Generated<Timestamp>;
	id: string;
	idToken: string | null;
	password: string | null;
	providerId: string;
	refreshToken: string | null;
	refreshTokenExpiresAt: Timestamp | null;
	scope: string | null;
	updatedAt: Timestamp;
	userId: string;
}

export interface Asset {
	bytes: number;
	createdAt: Generated<Timestamp>;
	folder: string | null;
	format: string;
	height: number | null;
	id: string;
	publicId: string;
	resourceType: string;
	secureUrl: string;
	url: string;
	width: number | null;
}

export interface AuditLog {
	action: string;
	createdAt: Generated<Timestamp>;
	details: Json | null;
	entity: string;
	entityId: string | null;
	id: string;
	ipAddress: string | null;
	userAgent: string | null;
	userId: string | null;
}

export interface Automation {
	content: string;
	coverImage: string | null;
	createdAt: Generated<Timestamp>;
	excerpt: string | null;
	fileUrl: string | null;
	id: string;
	published: Generated<boolean>;
	publishedAt: Timestamp | null;
	slug: string;
	title: string;
	updatedAt: Timestamp;
}

export interface AvailabilityBlock {
	createdAt: Generated<Timestamp>;
	endDate: Timestamp;
	id: string;
	reason: string | null;
	startDate: Timestamp;
}

export interface BlogPost {
	content: string;
	coverImage: string | null;
	createdAt: Generated<Timestamp>;
	excerpt: string | null;
	id: string;
	published: Generated<boolean>;
	publishedAt: Timestamp | null;
	slug: string;
	title: string;
	updatedAt: Timestamp;
}

export interface ComponentDoc {
	category: string;
	code: string;
	createdAt: Generated<Timestamp>;
	description: string | null;
	id: string;
	name: string;
	preview: string | null;
	props: Json;
	published: Generated<boolean>;
	slug: string;
	updatedAt: Timestamp;
}

export interface ComponentFile {
	componentId: string;
	content: string;
	createdAt: Generated<Timestamp>;
	filename: string;
	fileType: Generated<Filetype>;
	id: string;
	isMainFile: Generated<boolean>;
	order: Generated<number>;
	updatedAt: Timestamp;
}

export interface Contract {
	createdAt: Generated<Timestamp>;
	customerId: string;
	fileUrl: string;
	id: string;
	signatureData: string | null;
	signatureHash: string | null;
	signedAt: Timestamp | null;
	signerIp: string | null;
	signerName: string | null;
	status: Generated<Contractstatus>;
	title: string;
	updatedAt: Timestamp;
}

export interface Customer {
	companyName: string | null;
	createdAt: Generated<Timestamp>;
	id: string;
	leadId: string | null;
	phone: string | null;
	updatedAt: Timestamp;
	userId: string;
}

export interface EmailLog {
	body: string;
	id: string;
	sentAt: Generated<Timestamp>;
	status: Emailstatus;
	subject: string;
	to: string[] | null;
	userId: string;
}

export interface Icon {
	category: string;
	createdAt: Generated<Timestamp>;
	id: string;
	isCustom: Generated<boolean>;
	keywords: string[] | null;
	name: string;
	slug: string;
	svgContent: string;
	updatedAt: Timestamp;
}

export interface Invoice {
	amount: Numeric;
	createdAt: Generated<Timestamp>;
	customerId: string;
	description: string | null;
	dueDate: Timestamp | null;
	fileUrl: string;
	id: string;
	invoiceDate: Generated<Timestamp>;
	paidAt: Timestamp | null;
	projectId: string | null;
	status: Generated<Invoicestatus>;
	stripePaymentIntentId: string | null;
	updatedAt: Timestamp;
}

export interface Lead {
	budget: Budgetrange | null;
	createdAt: Generated<Timestamp>;
	currentStep: Generated<number>;
	details: string | null;
	email: string;
	id: string;
	name: string | null;
	projectType: Projecttype | null;
	source: string | null;
	status: Generated<Leadstatus>;
	surveyProgress: Json | null;
	updatedAt: Timestamp;
}

export interface LeadMagnet {
	assetId: string;
	createdAt: Generated<Timestamp>;
	description: string | null;
	id: string;
	isActive: Generated<boolean>;
	name: string;
	slug: string;
	updatedAt: Timestamp;
}

export interface Meeting {
	createdAt: Generated<Timestamp>;
	customerId: string | null;
	description: string | null;
	duration: number;
	eventId: string;
	id: string;
	leadId: string | null;
	meetUrl: string;
	scheduledAt: Timestamp;
	status: Generated<Meetingstatus>;
	title: string;
	updatedAt: Timestamp;
}

export interface Project {
	createdAt: Generated<Timestamp>;
	customerId: string;
	description: string | null;
	endDate: Timestamp | null;
	id: string;
	progress: Generated<number>;
	startDate: Timestamp | null;
	status: Generated<Projectstatus>;
	title: string;
	updatedAt: Timestamp;
}

export interface ProjectUpdate {
	content: string;
	createdAt: Generated<Timestamp>;
	id: string;
	progress: number | null;
	projectId: string;
	title: string;
}

export interface QAndA {
	answer: string | null;
	answeredAt: Timestamp | null;
	askedAt: Generated<Timestamp>;
	id: string;
	projectId: string;
	question: string;
}

export interface Session {
	createdAt: Generated<Timestamp>;
	expiresAt: Timestamp;
	id: string;
	ipAddress: string | null;
	token: string;
	updatedAt: Timestamp;
	userAgent: string | null;
	userId: string;
}

export interface SurveyOption {
	createdAt: Generated<Timestamp>;
	description: string | null;
	icon: string | null;
	id: string;
	isActive: Generated<boolean>;
	label: string;
	order: Generated<number>;
	questionId: string | null;
	questionType: Surveyquestiontype | null;
	updatedAt: Timestamp;
	value: string;
}

export interface SurveyQuestion {
	createdAt: Generated<Timestamp>;
	description: string | null;
	id: string;
	inputType: Generated<Surveyinputtype>;
	isActive: Generated<boolean>;
	key: string;
	order: Generated<number>;
	title: string;
	updatedAt: Timestamp;
}

export interface Tag {
	id: string;
	name: string;
	slug: string;
}

export interface User {
	createdAt: Generated<Timestamp>;
	email: string;
	emailVerified: Generated<boolean>;
	id: string;
	image: string | null;
	name: string;
	role: Generated<Role>;
	updatedAt: Timestamp;
}

export interface Verification {
	createdAt: Generated<Timestamp>;
	expiresAt: Timestamp;
	id: string;
	identifier: string;
	updatedAt: Timestamp;
	value: string;
}

export interface Webhook {
	createdAt: Generated<Timestamp>;
	events: string[] | null;
	id: string;
	isActive: Generated<boolean>;
	secret: string | null;
	updatedAt: Timestamp;
	url: string;
}

export interface WorkingHours {
	dayOfWeek: number;
	endTime: string;
	id: string;
	isEnabled: Generated<boolean>;
	startTime: string;
}

export interface DB {
	_AutomationToTag: _AutomationToTag;
	_BlogPostToTag: _BlogPostToTag;
	account: Account;
	asset: Asset;
	audit_log: AuditLog;
	automation: Automation;
	availability_block: AvailabilityBlock;
	blog_post: BlogPost;
	component_doc: ComponentDoc;
	component_file: ComponentFile;
	contract: Contract;
	customer: Customer;
	email_log: EmailLog;
	icon: Icon;
	invoice: Invoice;
	lead: Lead;
	lead_magnet: LeadMagnet;
	meeting: Meeting;
	project: Project;
	project_update: ProjectUpdate;
	q_and_a: QAndA;
	session: Session;
	survey_option: SurveyOption;
	survey_question: SurveyQuestion;
	tag: Tag;
	user: User;
	verification: Verification;
	webhook: Webhook;
	working_hours: WorkingHours;
}
