// GENERATED by scripts/materialize-bits-components.mjs — do not edit.
// Source of truth: registry/r/*.json (see scripts/build-bits-registry.mjs).

"use client";

import { ark } from "@ark-ui/react/factory";
import { cn } from "@/lib/utils";

export const Prose = (props: React.ComponentProps<typeof ark.div>) => {
  const { className, ...rest } = props;

  return (
    <ark.div
      className={cn("prose mx-auto max-w-[65ch]", className)}
      data-slot="prose"
      {...rest}
    />
  );
};
