import { Hono } from "hono";
import type { CloudflareEnv } from "../types/cloudflare";

/**
 * Dakik Icons CDN — public endpoints for the font kit on icons.dakik.co.uk:
 *
 *   GET /v1/da-icons.css   → the stylesheet third-party sites <link> to
 *   GET /v1/fonts/*.woff2  → the three icon fonts the stylesheet references
 *   GET /v1/icons.json     → machine-readable catalog
 *
 * The physical files live under /daicons/v1/ in the asset bundle (generated by
 * scripts/build-daicons-font.mjs, copied into dist/ by vite). This route gives
 * them the short canonical path on the icons subdomain and adds the headers
 * cross-origin consumers need: @font-face loads are CORS-gated, and the static
 * asset layer can't attach Access-Control-Allow-Origin. (The site-wide cors
 * middleware echoes the Origin header after this handler runs, which satisfies
 * font CORS too — the `*` set here covers origin-less requests like curl.)
 *
 * Same-origin loads from the icons browser page use /daicons/v1/* directly,
 * which bypasses the worker via a `run_worker_first` negative pattern.
 *
 * Like the bits registry, this is intentionally NOT host-gated: /v1/* is
 * unclaimed on every host, icons.dakik.co.uk is simply the documented URL
 * (and wrangler dev rewrites the Host header to the first custom domain,
 * which would defeat a host check locally).
 */
export function createDaiconsRouter() {
	const daicons = new Hono<{ Bindings: CloudflareEnv }>();

	daicons.get("/v1/*", async (c, next) => {
		const url = new URL(c.req.url);
		url.pathname = `/daicons${url.pathname}`;
		const res = await c.env.ASSETS.fetch(new Request(url.toString(), c.req.raw));
		// Unknown /v1/ path → fall through to the SPA catch-all (404 handling
		// there), instead of leaking the asset layer's SPA-shell fallback as CSS.
		if (!res.ok || res.headers.get("content-type")?.includes("text/html")) {
			return next();
		}

		// ASSETS responses have immutable headers — re-wrap before mutating.
		const out = new Response(res.body, res);
		out.headers.set("Access-Control-Allow-Origin", "*");
		out.headers.set(
			"Cache-Control",
			url.pathname.includes("/fonts/")
				? "public, max-age=31536000, immutable"
				: "public, max-age=3600, s-maxage=86400",
		);
		return out;
	});

	return daicons;
}
