/// <reference types="vite/client" />
import { type ComponentType, lazy } from "react";

/**
 * slug → lazily-loaded live demo, one chunk per bit. Guarded on SSR so the
 * worker bundle tree-shakes every demo (and @ark-ui / recharts with them) —
 * previews are mounted client-side only (see dacomps/detail.tsx).
 */
export const bitsDemos: Record<string, ComponentType | undefined> =
	import.meta.env.SSR
		? {}
		: {
			"accordion": lazy(() => import("./accordion")),
			"action-bar": lazy(() => import("./action-bar")),
			"alert": lazy(() => import("./alert")),
			"alert-dialog": lazy(() => import("./alert-dialog")),
			"announcement": lazy(() => import("./announcement")),
			"aspect-ratio": lazy(() => import("./aspect-ratio")),
			"autocomplete": lazy(() => import("./autocomplete")),
			"avatar": lazy(() => import("./avatar")),
			"badge": lazy(() => import("./badge")),
			"bottom-navigation": lazy(() => import("./bottom-navigation")),
			"breadcrumb": lazy(() => import("./breadcrumb")),
			"button": lazy(() => import("./button")),
			"button-group": lazy(() => import("./button-group")),
			"calendar": lazy(() => import("./calendar")),
			"card": lazy(() => import("./card")),
			"carousel": lazy(() => import("./carousel")),
			"chart": lazy(() => import("./chart")),
			"checkbox": lazy(() => import("./checkbox")),
			"circular-progress": lazy(() => import("./circular-progress")),
			"circular-slider": lazy(() => import("./circular-slider")),
			"clipboard": lazy(() => import("./clipboard")),
			"collapsible": lazy(() => import("./collapsible")),
			"color-picker": lazy(() => import("./color-picker")),
			"combobox": lazy(() => import("./combobox")),
			"command": lazy(() => import("./command")),
			"context-menu": lazy(() => import("./context-menu")),
			"data-list": lazy(() => import("./data-list")),
			"date-picker": lazy(() => import("./date-picker")),
			"dialog": lazy(() => import("./dialog")),
			"drawer": lazy(() => import("./drawer")),
			"editable": lazy(() => import("./editable")),
			"field": lazy(() => import("./field")),
			"file-upload": lazy(() => import("./file-upload")),
			"float": lazy(() => import("./float")),
			"floating-panel": lazy(() => import("./floating-panel")),
			"frame": lazy(() => import("./frame")),
			"hint": lazy(() => import("./hint")),
			"hover-card": lazy(() => import("./hover-card")),
			"image-cropper": lazy(() => import("./image-cropper")),
			"input": lazy(() => import("./input")),
			"input-group": lazy(() => import("./input-group")),
			"input-otp": lazy(() => import("./input-otp")),
			"item": lazy(() => import("./item")),
			"kbd": lazy(() => import("./kbd")),
			"link-overlay": lazy(() => import("./link-overlay")),
			"listbox": lazy(() => import("./listbox")),
			"marquee": lazy(() => import("./marquee")),
			"menu": lazy(() => import("./menu")),
			"native-select": lazy(() => import("./native-select")),
			"number-input": lazy(() => import("./number-input")),
			"pagination": lazy(() => import("./pagination")),
			"password-input": lazy(() => import("./password-input")),
			"popover": lazy(() => import("./popover")),
			"progress": lazy(() => import("./progress")),
			"prose": lazy(() => import("./prose")),
			"qr-code": lazy(() => import("./qr-code")),
			"radio-group": lazy(() => import("./radio-group")),
			"rating": lazy(() => import("./rating")),
			"resizable": lazy(() => import("./resizable")),
			"scroll-area": lazy(() => import("./scroll-area")),
			"segment-group": lazy(() => import("./segment-group")),
			"select": lazy(() => import("./select")),
			"separator": lazy(() => import("./separator")),
			"sheet": lazy(() => import("./sheet")),
			"sidebar": lazy(() => import("./sidebar")),
			"signature-pad": lazy(() => import("./signature-pad")),
			"skeleton": lazy(() => import("./skeleton")),
			"skip-nav": lazy(() => import("./skip-nav")),
			"slider": lazy(() => import("./slider")),
			"spinner": lazy(() => import("./spinner")),
			"status": lazy(() => import("./status")),
			"steps": lazy(() => import("./steps")),
			"switch": lazy(() => import("./switch")),
			"table": lazy(() => import("./table")),
			"tabs": lazy(() => import("./tabs")),
			"tags-input": lazy(() => import("./tags-input")),
			"textarea": lazy(() => import("./textarea")),
			"timer": lazy(() => import("./timer")),
			"toast": lazy(() => import("./toast")),
			"toggle": lazy(() => import("./toggle")),
			"toggle-group": lazy(() => import("./toggle-group")),
			"toggle-tooltip": lazy(() => import("./toggle-tooltip")),
			"tooltip": lazy(() => import("./tooltip")),
			"tour": lazy(() => import("./tour")),
			"tree-view": lazy(() => import("./tree-view")),
			"use-is-mobile": lazy(() => import("./use-is-mobile")),
			"utils": lazy(() => import("./utils")),
			};
