import { useQuery } from "@tanstack/react-query";
import { useHead } from "@unhead/react";
import { ArrowLeft, Check, Copy, Search } from "lucide-react";
import { useMemo, useState } from "react";
import Noise from "../components/noise";
import { DakikMark } from "../components/shared/dakik-mark";
import { pageHead } from "../lib/head";

/**
 * Dakik Icons — icon FONT kit browser (icons.dakik.co.uk).
 *
 * One stylesheet, three libraries, zero imports: add the <link>, then any
 * element with a `da-*` class renders a glyph. Material Icons own the plain
 * namespace (`da-book`), Phosphor and Lucide are prefixed (`da-ph-*`,
 * `da-lu-*`). Size defaults to 14px via `--da-size`; size classes (da-xs…,
 * da-10…da-64) set that variable, so they work per-icon or on any ancestor
 * as a page-wide default. Generated by scripts/build-daicons-font.mjs.
 */

const KIT_CSS_HREF = "/daicons/v1/da-icons.css";
const PUBLIC_CSS_URL = "https://icons.dakik.co.uk/v1/da-icons.css";

interface CatalogLibrary {
	id: string;
	label: string;
	classPrefix: string;
	license: string;
	source: string;
	version: string;
	count: number;
	icons: string[];
}

interface Catalog {
	version: number;
	sizes: {
		default: number;
		tshirt: Record<string, number>;
		pixels: number[];
	};
	libraries: CatalogLibrary[];
}

interface IconEntry {
	name: string;
	cls: string;
	lib: string;
}

async function fetchCatalog(): Promise<Catalog> {
	const res = await fetch("/daicons/v1/icons.json");
	if (!res.ok) throw new Error("Failed to load icon catalog");
	return res.json();
}

function useCopy(): [boolean, (text: string) => void] {
	const [copied, setCopied] = useState(false);
	const copy = (text: string) => {
		navigator.clipboard
			.writeText(text)
			.then(() => {
				setCopied(true);
				setTimeout(() => setCopied(false), 1200);
			})
			.catch(() => setCopied(false));
	};
	return [copied, copy];
}

function GlyphTile({ entry }: { entry: IconEntry }) {
	const [copied, copy] = useCopy();
	return (
		<button
			className="group relative flex aspect-square items-center justify-center border border-white/10 bg-transparent transition-colors hover:border-white hover:bg-white"
			onClick={() => copy(entry.cls)}
			title={`${entry.name} · ${entry.cls}`}
			type="button"
		>
			<i
				aria-hidden
				className={`${entry.cls} da-2xl text-white transition-colors group-hover:text-black`}
			/>
			<span className="pointer-events-none absolute right-1.5 bottom-1.5 text-white/0 group-hover:text-black/60">
				{copied ? <Check className="h-3 w-3" /> : <Copy className="h-3 w-3" />}
			</span>
		</button>
	);
}

function CodeBlock({ code, label }: { code: string; label?: string }) {
	const [copied, copy] = useCopy();
	return (
		<div className="border-2 border-white/15">
			<div className="flex items-center justify-between border-white/15 border-b px-4 py-2">
				<span className="font-mono text-[9px] text-white/45 uppercase tracking-[0.3em]">
					{label ?? "html"}
				</span>
				<button
					className="inline-flex items-center gap-2 font-mono text-[10px] text-white/55 uppercase tracking-[0.25em] transition-colors hover:text-white"
					onClick={() => copy(code)}
					type="button"
				>
					{copied ? <Check className="h-3 w-3" /> : <Copy className="h-3 w-3" />}
					{copied ? "Copied" : "Copy"}
				</button>
			</div>
			<pre className="overflow-x-auto px-4 py-3 text-[13px] text-white/85 leading-relaxed">
				<code>{code}</code>
			</pre>
		</div>
	);
}

const LIBRARY_TABS = [
	{ id: "all", label: "All" },
	{ id: "material", label: "Material" },
	{ id: "phosphor", label: "Phosphor" },
	{ id: "lucide", label: "Lucide" },
] as const;

const PAGE_SIZE = 396;

export function DaiconsPage() {
	const [search, setSearch] = useState("");
	const [lib, setLib] = useState<(typeof LIBRARY_TABS)[number]["id"]>("all");
	const [visible, setVisible] = useState(PAGE_SIZE);

	useHead({
		...pageHead({
			title: "Dakik Icons — 5,700+ font icons, one class, no imports",
			description:
				"One stylesheet, three icon libraries. Add a class like da-book and the glyph renders — Material, Phosphor and Lucide as a single icon-font kit.",
			canonical: "https://icons.dakik.co.uk/",
		}),
		link: [
			{ rel: "canonical", href: "https://icons.dakik.co.uk/" },
			{ rel: "stylesheet", href: KIT_CSS_HREF },
		],
	});

	const { data, isLoading } = useQuery({
		queryKey: ["daicons", "catalog"],
		queryFn: fetchCatalog,
		staleTime: Number.POSITIVE_INFINITY,
	});

	const entries = useMemo<IconEntry[]>(() => {
		if (!data) return [];
		return data.libraries.flatMap((l) =>
			l.icons.map((name) => ({
				name,
				cls: `${l.classPrefix}${name}`,
				lib: l.id,
			})),
		);
	}, [data]);

	const filtered = useMemo(() => {
		const byLib = lib === "all" ? entries : entries.filter((e) => e.lib === lib);
		if (!search) return byLib;
		const q = search.toLowerCase().trim();
		return byLib.filter((e) => e.name.includes(q) || e.cls.includes(q));
	}, [entries, lib, search]);

	const shown = filtered.slice(0, visible);
	const total = entries.length;

	return (
		<div className="relative min-h-screen overflow-hidden bg-black text-white">
			<header className="relative z-10 mx-auto flex items-center justify-between px-[clamp(1rem,5vw,4rem)] pt-10">
				<div className="flex items-center gap-3">
					<DakikMark className="h-9 w-auto shrink-0" />
					<div className="flex flex-col leading-none">
						<span className="font-black text-sm uppercase tracking-[-0.02em]">
							Dakik
						</span>
						<span className="font-mono text-[9px] text-white/45 uppercase tracking-[0.35em]">
							// Icons
						</span>
					</div>
				</div>
				<a
					className="group inline-flex items-center gap-2 font-mono text-[11px] text-white/55 uppercase tracking-[0.35em] transition-colors hover:text-white"
					href="https://dakik.co.uk"
				>
					<ArrowLeft className="size-3 transition-transform group-hover:-translate-x-0.5" />
					Dakik.co.uk
				</a>
			</header>

			<main className="relative z-10 mx-auto px-[clamp(1rem,5vw,4rem)] pt-16 pb-20">
				<section className="mb-12 max-w-3xl">
					<p className="font-mono text-[10px] text-white/55 uppercase tracking-[0.35em]">
						// One class. No imports.
					</p>
					<h1 className="mt-4 font-black text-[clamp(3rem,10vw,8rem)] uppercase leading-[0.85] tracking-[-0.04em]">
						Icons.
					</h1>
					<p className="mt-6 max-w-[56ch] text-base text-white/70 leading-snug sm:text-lg">
						{total > 0 ? `${total.toLocaleString()}+` : "5,700+"} icons from
						Material, Phosphor and Lucide as a single font kit. Add one
						stylesheet, then{" "}
						<code className="font-mono text-white/90">
							&lt;i class="da-book"&gt;&lt;/i&gt;
						</code>{" "}
						just renders — no imports, no SVG sprites, no build step.
					</p>
				</section>

				<section className="mb-16 grid max-w-4xl gap-4">
					<CodeBlock
						label="1 — add the kit"
						code={`<link rel="stylesheet" href="${PUBLIC_CSS_URL}">`}
					/>
					<CodeBlock
						label="2 — use any icon"
						code={[
							`<i class="da-book"></i>              <!-- Material (default), 14px -->`,
							`<i class="da-ph-book da-xl"></i>     <!-- Phosphor, 20px -->`,
							`<i class="da-lu-book-open da-24"></i><!-- Lucide, 24px -->`,
						].join("\n")}
					/>
				</section>

				<div className="mb-6 flex flex-wrap items-center gap-3">
					{LIBRARY_TABS.map((t) => (
						<button
							className={`border-2 px-4 py-2 font-mono text-[10px] uppercase tracking-[0.25em] transition-colors ${
								lib === t.id
									? "border-white bg-white text-black"
									: "border-white/20 text-white/60 hover:border-white hover:text-white"
							}`}
							key={t.id}
							onClick={() => {
								setLib(t.id);
								setVisible(PAGE_SIZE);
							}}
							type="button"
						>
							{t.label}
						</button>
					))}
				</div>

				<div className="mb-8 flex max-w-md items-center gap-3 border-2 border-white/20 px-4 py-3 transition-colors focus-within:border-white">
					<Search className="h-4 w-4 text-white/40" />
					<input
						className="w-full bg-transparent text-sm text-white outline-none placeholder:text-white/30"
						onChange={(e) => {
							setSearch(e.target.value);
							setVisible(PAGE_SIZE);
						}}
						placeholder="Search 5,700+ icons…"
						value={search}
					/>
					<span className="font-mono text-[10px] text-white/40 uppercase tracking-[0.25em] tabular-nums">
						{filtered.length}
					</span>
				</div>

				{isLoading && (
					<p className="font-mono text-[11px] text-white/55 uppercase tracking-[0.35em]">
						// Loading icons…
					</p>
				)}

				{!isLoading && (
					<>
						<p className="mb-4 font-mono text-[10px] text-white/40 uppercase tracking-[0.3em]">
							// Click a tile to copy its class
						</p>
						<div className="grid grid-cols-4 gap-2 sm:grid-cols-6 md:grid-cols-8 lg:grid-cols-10 xl:grid-cols-12">
							{shown.map((e) => (
								<GlyphTile entry={e} key={e.cls} />
							))}
						</div>
						{filtered.length > visible && (
							<div className="mt-8 flex items-center gap-4">
								<button
									className="border-2 border-white/20 px-6 py-3 font-mono text-[10px] uppercase tracking-[0.25em] text-white/70 transition-colors hover:border-white hover:text-white"
									onClick={() => setVisible((v) => v + PAGE_SIZE)}
									type="button"
								>
									Load more
								</button>
								<span className="font-mono text-[10px] text-white/40 uppercase tracking-[0.25em] tabular-nums">
									{shown.length} / {filtered.length}
								</span>
							</div>
						)}
					</>
				)}

				{!isLoading && filtered.length === 0 && (
					<p className="mt-10 font-mono text-[11px] text-white/55 uppercase tracking-[0.35em]">
						// Nothing matches "{search}"
					</p>
				)}

				<section className="mt-20 grid max-w-4xl gap-12 border-white/10 border-t pt-10">
					<div>
						<p className="font-mono text-[10px] text-white/55 uppercase tracking-[0.35em]">
							// Sizing
						</p>
						<p className="mt-4 max-w-[64ch] text-base text-white/70 leading-snug">
							Icons render at <code className="font-mono text-white/90">14px</code>{" "}
							by default. Size classes set the{" "}
							<code className="font-mono text-white/90">--da-size</code> variable,
							so the same class works per icon{" "}
							<em className="not-italic text-white/90">or</em> on any ancestor as a
							page-wide default — put{" "}
							<code className="font-mono text-white/90">class="da-16"</code> on{" "}
							<code className="font-mono text-white/90">&lt;html&gt;</code> and every
							unsized icon becomes 16px.
						</p>
						<div className="mt-6 grid gap-4">
							<CodeBlock
								label="t-shirt sizes"
								code={`da-xs 10px · da-sm 12px · da-md 14px · da-lg 16px · da-xl 20px · da-2xl 24px · da-3xl 32px · da-4xl 40px · da-5xl 48px`}
							/>
							<CodeBlock
								label="pixel sizes"
								code={`da-10 da-12 da-14 da-16 da-18 da-20 da-22 da-24 da-28 da-32 da-36 da-40 da-48 da-56 da-64`}
							/>
							<CodeBlock
								label="global default + arbitrary values"
								code={[
									`<html class="da-16">                <!-- all unsized icons → 16px -->`,
									`<i class="da-book" style="--da-size: 17px"></i>  <!-- any value -->`,
								].join("\n")}
							/>
						</div>
					</div>

					<div>
						<p className="font-mono text-[10px] text-white/55 uppercase tracking-[0.35em]">
							// Libraries &amp; colour
						</p>
						<p className="mt-4 max-w-[64ch] text-base text-white/70 leading-snug">
							Plain names (<code className="font-mono text-white/90">da-book</code>)
							come from Material Icons.{" "}
							<code className="font-mono text-white/90">da-ph-*</code> is Phosphor,{" "}
							<code className="font-mono text-white/90">da-lu-*</code> is Lucide.
							Icons are text — they inherit{" "}
							<code className="font-mono text-white/90">currentColor</code>, so style
							them with your usual <code className="font-mono text-white/90">color</code>.
							Only the fonts you actually use get downloaded.
						</p>
					</div>
				</section>
			</main>

			<footer className="relative z-10 mx-auto flex flex-wrap items-center justify-between gap-3 border-white/10 border-t px-[clamp(1rem,5vw,4rem)] py-8">
				<span className="font-mono text-[10px] text-white/40 uppercase tracking-[0.35em]">
					// Material Icons · Apache-2.0 — Phosphor · MIT — Lucide · ISC
				</span>
				<a
					className="font-mono text-[10px] text-white/40 uppercase tracking-[0.35em] transition-colors hover:text-white"
					href="https://dakik.co.uk"
				>
					Dakik Studio →
				</a>
			</footer>

			<Noise patternAlpha={15} patternRefreshInterval={4} />
		</div>
	);
}

export default DaiconsPage;
