// GENERATED by scripts/materialize-bits-components.mjs — do not edit.
// Source of truth: registry/r/*.json (see scripts/build-bits-registry.mjs).

import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export const cn = (...inputs: ClassValue[]) => twMerge(clsx(inputs));
